image: stockflare/jekyll:0.4.0
script:
  - jekyll build --destination out
  - s3cmd --access_key=$$access_key_id --secret_key=$$secret_access_key --acl-public put --recursive out/ s3://quotes.stockflare.com/
notify:
  flowdock:
    source: Drone
    token: $$flowdock_token
    tags: drone
    on_started: true
    on_success: true
    on_failure: true
