# Site settings
title: Quotes from Masters of the Financial Universe
email: info@stockflare.com
description: "Check out over 175 maxims and quotes from Masters of the Financial Universe. Including Warren Buffett, John Neff, Bernard Baruch, Howard Marks and many more."
baseurl: ""
url: "http://quotes.stockflare.com"

# Build settings
markdown: kramdown
permalink: pretty
